server:
  port: 8080
#Database / Hibernate / JPA
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/application?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    driver: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
    show-sql: true